export const ROUTES = {
  HOME_PATH: '/',
  GIFT: '/gift',
  SLOT: '/slot',
  TEAM: '/team',
  MARKET: '/market',
  CREDIT: '/credit',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  PROFILE: '/profile',
  NOT_FOUND_PAGE: '*',
  HAMSTER: '/hamster',
  DEPOSIT: '/deposit',
  WIDTDRAW: '/widthdraw',
  REPLENISH: '/replenish',
  CHECK_IN_GIFT: '/check-in-gift',
  ADD_BANK_CARD: '/add-bank-card',
  WIDTDRAW_LIST: '/widtdraw-list',
  CHANGE_PASSWORD: '/change-password',
  ABOUT_OUR_PROJECT: '/about-our-project',
  WIDTDRAW_PASSWORD: '/widtdraw-password',
} as const;
