export const ROUTES = {
  HOME_PATH: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  PROFILE: '/profile',
  NOT_FOUND_PAGE: '*',
  GIFT: '/gift',
  HAMSTER: '/hamster',
  MARKET: '/market',
  TEAM: '/team',
  REPLENISH: '/replenish',
  WIDTDRAW: '/widthdraw',
  CREDIT: '/credit',
  DEPOSIT: '/deposit',
  SLOT: '/slot',
  CHECK_IN_GIFT: '/check-in-gift',
  ABOUT_OUR_PROJECT: '/about-our-project',
} as const;
